#!/bin/bash -
echo "Destroying cloud infrastructure"
pushd terraform
	terraform init
	terraform destroy -auto-approve
popd
echo "============================================================"
echo "Application and infrastructure removed"
echo "============================================================"
